---
title: '20190417'
author: "JTRF"
date: "2019/4/17"
output: html_document
---

＃Recursive objects
```{r}
studentRecord <-
  list(
    學號="410073058",#用逗號分出元素
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

#Object extraction
```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```
```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```

```{r}
your_github_username <- "tpemartin"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))

```

```{r}
commitCheckStatement
commitCheck

```

#回家去找Date 右邊格藍色箭頭去找第四格commiter date


```{r}
library(readr)
library(stringr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```

```{r}
library(stringr)
str_split(favoriteTwo,", ") -> favoriteTwoList # 將選擇的兩片split成兩個元素
unlist(favoriteTwoList) -> allVotes # 將list堆疊成atomic vector
table(allVotes) # 計算每個類別的次數

logicorrect<-str_length(birthday)==8
favoriteTwo[logicorrect] -> validFavoriteTwo
validFavoriteTwo
```
```{r}

```

